### ISSUE TITLE
Support of UPSERT using ON CONFICT DO UPDATE ?

### ISSUE THREAD

**Issue by MatthieuTexier** [matthijs/sqlpp11-connector-postgresql#48] opened 2018-04-07 06:08 UTC
Postgresql >= 9.5 support UPSERT feature (update or insert) using INSERT ... ON CONFLICT DO UPDATE SET ...
This doesn't look easy to implement in sqlpp11, is there any one working on that feature?

**Comment by matthijs** [comment] 2018-04-12 12:28
Not yet, but I know there is some sort of support available in the sqlite3 connector.

I'll try to come up with a solution.

**Comment by gagbo** [comment] 2019-07-14 10:12
Is there something I can do to start helping on this ? I'm needing to have at least an `ON CONFLICT DO NOTHING` for insert for my cases (it would reduce the number of actual db connections my program needs).

I've been reading here and there but I don't really know where to start to contribute :(

**Comment by matthijs** [comment] 2019-07-15 11:48
I am implementing this feature, hopefully I can finish it this evening.

**Comment by matthijs** [comment] 2019-07-28 21:49
See the feature/upsert branch. This is still work in progress but statements like following are working:
```c++
namespace sql = sqlpp::postgresql;

model::TabFoo foo = {};
auto insert1 = sql::insert_into(foo).default_values().on_conflict().do_nothing();
auto insert2 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true);
```

There are still some TODO's:

- The where statement is still missing on 'DO UPDATE SET .. WHERE ..'
- Various checks on the parameters

Be careful, I've disabled all tests except for InsertOrConflict.

**Comment by gagbo** [comment] 2019-07-28 22:23
That's more than enough for me now ! I'll start using this in my project I think, and see how it goes :)

**Comment by MatthieuTexier** [comment] 2019-07-29 07:18
Great ! It's already a game changer ;-)

**Comment by gagbo** [comment] 2019-07-29 18:32
The `returning` statement doesn't work :
```cpp
auto insert2 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true).returning(foo.beta);
std::cout << insert2.beta();
```
won't compile, because it'll say there's no member named `beta` in the `statement_t< template hell >`. The `returning_column_list` and the `on_conflict` markers are both in the statement_t.

I just piggy-backed on this example from my compile error, tell me if you can't reproduce it

**Comment by gagbo** [comment] 2019-07-29 19:16
The full error in my case (just in case) :
```
/home/gagbo/projects/learning/mowglimmo/apps/db_filler.cpp:217:53:
        error:
        no member named 'id' in
        'sqlpp::statement_t<
                void,
                sqlpp::insert_t,
                sqlpp::into_t<void, mowglimmo::dvf::adresse>,
                sqlpp::insert_list_t<
                       void,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Numero_voie>,
                              sqlpp::value_or_null_t<sqlpp::integral> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Indice_repetition>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Type_voie>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Code_voie>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Nom_voie>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Code_postal>,
                              sqlpp::value_or_null_t<sqlpp::integral> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Commune>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Code_dept>,
                              sqlpp::tvin_arg_t<sqlpp::text_operand> >,
                       sqlpp::assignment_t<
                              sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Code_commune>,
                              sqlpp::value_or_null_t<sqlpp::integral> > >,
                sqlpp::postgresql::returning_column_list_t<void, sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Id> >,
                sqlpp::postgresql::on_conflict_do_update_t<void, sqlpp::assignment_t<sqlpp::column_t<mowglimmo::dvf::adresse, mowglimmo::dvf::adresse_::Code_dept>, sqlpp::tvin_arg_t<sqlpp::text_operand> > > >'
```

**Comment by matthijs** [comment] 2019-07-29 19:25
How did you get the error reporting so nicely formatted?

At my place it compiles correctly and produces the following:
```c++
namespace sql = sqlpp::postgresql;

model::TabFoo foo = {};
MockDb::_serializer_context_t printer = {};

auto insert4 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true).returning(foo.beta);
std::cout << serialize(insert4, printer).str() << std::endl;
```

Output:
```sql
INSERT INTO TabFoo DEFAULT VALUES RETURNING TabFoo.beta ON CONFLICT DO UPDATE SET beta=5,gamma='test bla',c_bool=1
```

**Comment by gagbo** [comment] 2019-07-29 19:40
I copypasted the error and formatted by hand, I had to check this :p

Good to know that it compiles on your end, I'll try to understand what's wrong here.

**Comment by matthijs** [comment] 2019-07-29 19:53
Ah, I currently just print the statement, did you forget to execute the query on the database and use the result?
```c++
namespace sql = sqlpp::postgresql;

model::TabFoo foo = {};
MockDb::_serializer_context_t printer = {};

auto insert4 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true).returning(foo.beta);
std::cout << serialize(insert4, printer).str() << std::endl;

auto config = std::make_shared<sql::connection_config>();
sql::connection db(config);
std::cout << db(insert4).front().beta << std::endl;
```

**Comment by gagbo** [comment] 2019-07-29 19:55
Oh right. That's why. I need to use a prepared statement to use the `adresse.id()` as an argument of another insert ?

**Comment by matthijs** [comment] 2019-07-29 20:09
Something like this?
```c++
namespace sql = sqlpp::postgresql;

model::TabFoo foo = {};
MockDb::_serializer_context_t printer = {};

auto insert4 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = parameter(foo.beta), foo.gamma = parameter(foo.gamma), foo.c_bool = parameter(foo.c_bool)).returning(foo.beta);
std::cout << serialize(insert4, printer).str() << std::endl;

auto config = std::make_shared<sql::connection_config>();
sql::connection db(config);
auto prepared = db.prepare(insert4);
prepared.params.beta = 8;
prepared.params.gamma = "some more text";
prepared.params.c_bool = false;
auto result = db(prepared);
std::cout << db(insert4).front().beta << std::endl; // if this fails:
std::cout << db(insert4).front().beta.value() << std::endl;
```

**Comment by gagbo** [comment] 2019-07-29 20:31
I guess. I'll try to make something work, and I'll show some code

**Comment by gagbo** [comment] 2019-07-29 20:59
The `ON CONFLICT DO UPDATE SET` will probably need more work, since the `conflict_target` parameter is mandatory for `DO UPDATE`, at least in [Postgres 11](https://www.postgresql.org/docs/11/sql-insert.html#SQL-ON-CONFLICT).

**Comment by matthijs** [comment] 2019-07-30 08:38
You are right, I just tested the statement and it should be like:
```sql
INSERT INTO domains (id, name, type) VALUES (3, 'somedomain.com', 'MASTER')
  ON CONFLICT (id) DO UPDATE SET type = 'NATIVE';
```
I had the WHERE for 'DO UPDATE' almost working, but this needs some extra work. I'll first finish the 'WHERE' part and after that I will look into this.

**Comment by matthijs** [comment] 2019-07-30 17:53
I've now added the WHERE statement, can be used as follows:
```c++
namespace sql = sqlpp::postgresql;

model::TabFoo foo = {};
MockDb::_serializer_context_t printer = {};

// With where statement
auto insert3 = sql::insert_into(foo).default_values().on_conflict().do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true).where(foo.beta == 2);
std::cout << serialize(insert3, printer).str() << std::endl;
printer.reset();
```
Output:
```sql
INSERT INTO TabFoo DEFAULT VALUES
  ON CONFLICT DO UPDATE SET beta=5,gamma='test bla',c_bool=1 WHERE (TabFoo.beta=2)
```
The only part missing is the conflict_target, I'll take a look at that now.

**Comment by matthijs** [comment] 2019-08-01 17:50
The conflict_target is partially implemented, the documentation of postgresql says:
```
where conflict_target can be one of:

    ( { index_column_name | ( index_expression ) } [ COLLATE collation ] [ opclass ] [, ...] ) [ WHERE index_predicate ]
    ON CONSTRAINT constraint_name
```
Only the first part is supported, 'index_column_name'. In c++ this looks like:
```c++
namespace sql = sqlpp::postgresql;
model::TabFoo foo = {};
MockDb::_serializer_context_t printer = {};

// With where statement
auto insert3 = sql::insert_into(foo)
                   .default_values()
                   .on_conflict(foo.beta)
                   .do_update(foo.beta = 5, foo.gamma = "test bla", foo.c_bool = true)
                   .where(foo.beta == 2)
                   .returning(foo.gamma);
std::cout << serialize(insert3, printer).str() << std::endl;
printer.reset();
```
Output:
```sql
INSERT INTO TabFoo DEFAULT VALUES 
  ON CONFLICT (TabFoo.beta) DO UPDATE SET beta=5,gamma='test bla',c_bool=1 WHERE (TabFoo.beta=2)
  RETURNING TabFoo.gamma
```
The last part to implement will be the compile time checks to see if the parameters are correct.

Let me know if there are any problems...

**Comment by matthijs** [comment] 2019-08-03 18:00
The compile time checks are also implemented.

For now the implementation of 'UPSERT' (INSERT INTO .. ON CONFLICT ..) is complete. The only limitation is the conflict_target. The conflict_target only supports a column. If there is need for a more sophisticated conflict_target please open a separate issue.

**Comment by matthijs** [comment] 2019-08-04 12:24
Merged into master.

**Closed by matthijs** 2019-08-04 12:24 UTC

**Comment by MatthieuTexier** [comment] 2019-08-04 13:29
Thank you, it's a great feature, I will try this very soon.
